- run:
  name: Set application-specific environment variables in Elastic Beanstalk
  command: |
    # Define a pattern for allowed variables, adjusting as needed for your app's variables
    ALLOWED_VARS=("POSTGRES_HOST" "POSTGRES_PORT" "POSTGRES_USERNAME" "POSTGRES_PASSWORD" "AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY" "AWS_REGION" "JWT_SECRET")

    # Initialize valid variables string
    VALID_VARS=""

    # Loop through allowed environment variables
    for VAR in "${ALLOWED_VARS[@]}"; do
      VALUE=$(printenv "$VAR")

      # Validate that each variable is not empty or masked
      if [[ -n "$VALUE" && "$VALUE" != "********" ]]; then
        VALID_VARS+="$VAR=$VALUE "
      else
        echo "Skipping invalid or empty variable: $VAR"
      fi
    done

    # Ensure we have valid variables to set
    if [[ -z "$VALID_VARS" ]]; then
      echo "No valid environment variables to set. Exiting."
      exit 1
    else
      echo "Setting valid environment variables in Elastic Beanstalk: $VALID_VARS"
      
      # Set each environment variable individually to catch syntax issues
      for ENV_VAR in
